CREATE SCHEMA BDVENDA;

USE BDVENDA;

CREATE TABLE FORN_FORNECEDOR (
  FORN_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  FORN_NOME VARCHAR(50) NOT NULL,
  FORN_CNPJ VARCHAR(18) NOT NULL,
  FORN_ENDERECO VARCHAR(100) NOT NULL,
  FORN_TELEFONE VARCHAR(14) NOT NULL,
  CONSTRAINT FORN_FORNECEDOR_PK PRIMARY KEY (FORN_ID),
  CONSTRAINT FORN_CNPJ_UK UNIQUE KEY (FORN_CNPJ)
);

CREATE TABLE PROD_PRODUTO(
  PROD_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  FORN_ID BIGINT UNSIGNED NOT NULL,
  PROD_NOME VARCHAR(50) NOT NULL,
  PROD_PRECO REAL UNSIGNED NOT NULL,
  PROD_CATEGORIA VARCHAR(11) NOT NULL,
  CONSTRAINT PROD_PRODUTO_PK PRIMARY KEY (PROD_ID),
  FOREIGN KEY PROD_FORNECEDOR_FK (FORN_ID) REFERENCES FORN_FORNECEDOR (FORN_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);


CREATE TABLE VEN_VENDA (
  VEN_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  VEN_DATA DATE NOT NULL,
  CONSTRAINT pk_venda PRIMARY KEY (ven_id) 
);

CREATE TABLE VPV_VENDA_PRODUTO (
  VEN_ID BIGINT UNSIGNED NOT NULL,
  PROD_ID BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY(VEN_ID, PROD_ID),
  FOREIGN KEY VPV_VENDA_FK (VEN_ID) REFERENCES VEN_VENDA(VEN_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY VPV_PRODUTO_FK (PROD_ID) REFERENCES PROD_PRODUTO(PROD_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);