DROP SCHEMA BDVENDA;

CREATE SCHEMA BDVENDA;

USE BDVENDA;

CREATE TABLE FORN_FORNECEDOR (
  FORN_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  FORN_NOME VARCHAR(50) NOT NULL,
  FORN_CNPJ VARCHAR(18) NOT NULL,
  FORN_ENDERECO VARCHAR(100) NOT NULL,
  FORN_TELEFONE VARCHAR(14) NOT NULL,
  CONSTRAINT FORN_FORNECEDOR_PK PRIMARY KEY (FORN_ID),
  CONSTRAINT FORN_CNPJ_UK UNIQUE KEY (FORN_CNPJ)
);

CREATE TABLE PROD_PRODUTO(
  PROD_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  FORN_ID BIGINT UNSIGNED NOT NULL,
  PROD_NOME VARCHAR(50) NOT NULL,
  PROD_PRECO REAL UNSIGNED NOT NULL,
  PROD_CATEGORIA VARCHAR(11) NOT NULL,
  CONSTRAINT PROD_PRODUTO_PK PRIMARY KEY (PROD_ID),
  FOREIGN KEY PROD_FORNECEDOR_FK (FORN_ID) REFERENCES FORN_FORNECEDOR (FORN_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE CLI_CLIENTE (
  CLI_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  CLI_NOME VARCHAR(50) NOT NULL,
  CLI_SOBRENOME VARCHAR(50) NOT NULL,
  CLI_TELEFONE VARCHAR(14) NOT NULL,
  CONSTRAINT CLI_CLIENTE_PK PRIMARY KEY(CLI_ID)
);


CREATE TABLE VEN_VENDA (
  VEN_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  CLI_ID BIGINT UNSIGNED NOT NULL,
  VEN_DATA DATE NOT NULL,
  CONSTRAINT pk_venda PRIMARY KEY (ven_id),
  FOREIGN KEY VEN_CLI_FK (CLI_ID) REFERENCES CLI_CLIENTE (CLI_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE VPV_VENDA_PRODUTO (
  VEN_ID BIGINT UNSIGNED NOT NULL,
  PROD_ID BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY(VEN_ID, PROD_ID),
  FOREIGN KEY VPV_VENDA_FK (VEN_ID) REFERENCES VEN_VENDA(VEN_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY VPV_PRODUTO_FK (PROD_ID) REFERENCES PROD_PRODUTO(PROD_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

INSERT INTO FORN_FORNECEDOR VALUES (0,"Samsung", "123456789", "Rua 21 de Abril", "(12) 3926-6584");
INSERT INTO FORN_FORNECEDOR VALUES (0,"Nike", "985654875", "Avenida 7 de Setembro", "(12) 3655-9651");
INSERT INTO FORN_FORNECEDOR VALUES (0,"Nestle", "125558789", "Avenida Paulista", "(12) 3654-9874");
INSERT INTO FORN_FORNECEDOR VALUES (0,"Adidas", "659875412", "Rua Marechal Rondon", "(12) 3655-9874");
INSERT INTO FORN_FORNECEDOR VALUES (0,"LG", "125478541", "Rua Cantidio Miragaia", "(12) 3655-9658");

INSERT INTO PROD_PRODUTO VALUES(0, 1, "Computador I7 Samsung", 2693.99, "ELETRONICOS");
INSERT INTO PROD_PRODUTO VALUES(0, 1, "Computador I3 Samsung", 1992.99, "ELETRONICOS");
INSERT INTO PROD_PRODUTO VALUES(0, 2, "Camiseta G Nike Sports", 49.90, "VESTIMENTAS");
INSERT INTO PROD_PRODUTO VALUES(0, 3, "Chocolate Diamante Negro", 15.99, "ALIMENTOS");
INSERT INTO PROD_PRODUTO VALUES(0, 3, "Achocolatado em pó Nescau", 7.99, "ALIMENTOS");
INSERT INTO PROD_PRODUTO VALUES(0, 4, "Meia Adidas tamanho 41", 17.99, "VESTIMENTAS");
INSERT INTO PROD_PRODUTO VALUES(0, 4, "Blusa de Frio Adidas", 269.90, "VESTIMENTAS");

INSERT INTO CLI_CLIENTE VALUES(0,"Daniel", "Correa", "(12) 3699-6595");
INSERT INTO CLI_CLIENTE VALUES(0,"Fernanda", "Batista", "(12) 3622-6585");
INSERT INTO CLI_CLIENTE VALUES(0,"Gilberto", "Ferraz", "(12) 3655-1478");
INSERT INTO CLI_CLIENTE VALUES(0,"Rafaela", "Rodriguez", "(12) 3222-6698");
INSERT INTO CLI_CLIENTE VALUES(0,"Marcela", "Fernandez", "(12) 3169-6954");
INSERT INTO CLI_CLIENTE VALUES(0,"Alexandre", "Muniz", "(12) 3661-5654");
INSERT INTO CLI_CLIENTE VALUES(0,"Rodrigo", "Celestino", "(12) 3666-5214");
INSERT INTO CLI_CLIENTE VALUES(0,"Higor", "Fortunato", "(12) 3458-6587");

INSERT INTO VEN_VENDA VALUES(0,2, STR_TO_DATE( "31/05/2014", "%d/%m/%Y" ));
INSERT INTO VEN_VENDA VALUES(0,5, STR_TO_DATE( "20/07/2012", "%d/%m/%Y" ));
INSERT INTO VEN_VENDA VALUES(0,4, STR_TO_DATE( "05/12/2011", "%d/%m/%Y" ));
INSERT INTO VEN_VENDA VALUES(0,1, STR_TO_DATE( "03/04/2013", "%d/%m/%Y" ));
INSERT INTO VEN_VENDA VALUES(0,3, STR_TO_DATE( "11/05/2016", "%d/%m/%Y" ));

INSERT INTO VPV_VENDA_PRODUTO VALUES (1, 5);
INSERT INTO VPV_VENDA_PRODUTO VALUES (1, 3);
INSERT INTO VPV_VENDA_PRODUTO VALUES (1, 1);
INSERT INTO VPV_VENDA_PRODUTO VALUES (2, 2);
INSERT INTO VPV_VENDA_PRODUTO VALUES (2, 6);
INSERT INTO VPV_VENDA_PRODUTO VALUES (3, 7);
INSERT INTO VPV_VENDA_PRODUTO VALUES (3, 5);
INSERT INTO VPV_VENDA_PRODUTO VALUES (4, 3);
INSERT INTO VPV_VENDA_PRODUTO VALUES (5, 2);
INSERT INTO VPV_VENDA_PRODUTO VALUES (5, 1);
